# Generated by Django 4.2.5 on 2024-05-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.CharField(default='', max_length=300),
        ),
    ]
